// DT-verified testbench for raster_dsp_mul
// Combinational: signed 17-bit × unsigned 18-bit → signed 36-bit
// Loads test vectors from hex files generated by the digital twin.

`timescale 1ns/1ps

module tb_dsp_mul_dt;

    // DUT signals (combinational — no clock needed for DUT)
    reg  signed [16:0] a;
    reg         [17:0] b;
    wire signed [35:0] p;

    // Instantiate DUT
    raster_dsp_mul dut (
        .a (a),
        .b (b),
        .p (p)
    );

    // Test vector storage
    // Stimulus format: "AAAAAAAA_BBBBBBBB" (two 32-bit hex words per line)
    // We load as 64-bit words split into two 32-bit arrays
    parameter MAX_VECTORS = 512;
    reg [63:0] stim_mem [0:MAX_VECTORS-1];
    reg [63:0] exp_mem  [0:MAX_VECTORS-1];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    initial begin
        $readmemh("../rtl/components/rasterizer/tests/vectors/dsp_mul_stim.hex", stim_mem);
        $readmemh("../rtl/components/rasterizer/tests/vectors/dsp_mul_exp.hex", exp_mem);

        // First entry is the vector count (lower 32 bits)
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            a = stim_mem[i + 1][49:32];  // Upper word: a[16:0] in bits [49:32]
            b = stim_mem[i + 1][17:0];   // Lower word: b[17:0] in bits [17:0]
            #1; // Allow combinational propagation

            begin
                reg signed [35:0] exp_p;
                exp_p = exp_mem[i + 1][35:0];

                if (p === exp_p) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: a=%0d b=%0d expected p=%0d, got p=%0d",
                             i, $signed(a), b, $signed(exp_p), $signed(p));
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_dsp_mul_dt: %0d vectors, PASS=%0d FAIL=%0d", num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule
