// DT-verified testbench for texture_cache_l1 (WRAP addressing mode)
//
// Loads test vectors from hex files generated by the digital twin
// (gen_l1_cache_wrap_vectors). Verifies that RTL output matches
// the twin's expected UQ1.8 texel values at the bank outputs.
//
// Test vectors use RGB565 format (tex_format=5, burst_len=16 words).
// Fill operations trigger a cache miss then model the SRAM interface
// to deliver burst data. Lookup operations verify hit + texel data.
//
// Signal drive convention: all DUT inputs are driven on @(negedge clk)
// so they are stable well before the DUT's posedge-triggered flip-flops.

`default_nettype none

module tb_l1_cache_wrap_dt;

    // ========================================================================
    // Constants
    // ========================================================================

    localparam CLK_PERIOD = 10;               // 100 MHz (10 ns period)
    localparam MAX_OPS    = 512;              // Maximum operations
    localparam MAX_STIM_WORDS = MAX_OPS * 9; // Header + up to 8 data words per fill
    localparam MAX_EXP_WORDS  = MAX_OPS * 4; // 4 texels per lookup

    // ========================================================================
    // Test Counters
    // ========================================================================

    integer pass_count = 0;
    integer fail_count = 0;

    // ========================================================================
    // DUT Signals
    // ========================================================================

    reg         clk;
    reg         rst_n;

    // Lookup request
    reg         lookup_req;
    reg  [9:0]  pixel_x;
    reg  [9:0]  pixel_y;
    reg  [23:0] tex_base_addr;
    reg  [2:0]  tex_format;
    reg  [7:0]  tex_width_log2;

    // Lookup result
    wire        cache_hit;
    wire        cache_ready;
    wire [35:0] texel_out_0;
    wire [35:0] texel_out_1;
    wire [35:0] texel_out_2;
    wire [35:0] texel_out_3;

    /* verilator lint_off UNUSEDSIGNAL */
    wire        data_valid;     // Used for waveform debugging
    wire        fill_done;      // Used for waveform debugging
    wire        sram_we;        // Read-only port, always 0
    wire [31:0] sram_wdata;     // Read-only port, always 0
    wire [23:0] sram_addr;      // Observed in SRAM responder
    wire        sram_req;       // Used in sram_respond task
    wire [7:0]  sram_burst_len; // Used in sram_respond task
    /* verilator lint_on UNUSEDSIGNAL */

    // Invalidation
    reg         invalidate;
    reg  [15:0] sram_burst_rdata;
    reg         sram_burst_data_valid;
    reg         sram_ack;
    reg         sram_ready;

    // ========================================================================
    // DUT Instantiation
    // ========================================================================

    texture_cache_l1 dut (
        .clk                 (clk),
        .rst_n               (rst_n),
        .lookup_req          (lookup_req),
        .pixel_x             (pixel_x),
        .pixel_y             (pixel_y),
        .tex_base_addr       (tex_base_addr),
        .tex_format          (tex_format),
        .tex_width_log2      (tex_width_log2),
        .cache_hit           (cache_hit),
        .data_valid          (data_valid),
        .cache_ready         (cache_ready),
        .fill_done           (fill_done),
        .texel_out_0         (texel_out_0),
        .texel_out_1         (texel_out_1),
        .texel_out_2         (texel_out_2),
        .texel_out_3         (texel_out_3),
        .invalidate          (invalidate),
        .sram_req            (sram_req),
        .sram_addr           (sram_addr),
        .sram_burst_len      (sram_burst_len),
        .sram_we             (sram_we),
        .sram_wdata          (sram_wdata),
        .sram_burst_rdata    (sram_burst_rdata),
        .sram_burst_data_valid(sram_burst_data_valid),
        .sram_ack            (sram_ack),
        .sram_ready          (sram_ready)
    );

    // ========================================================================
    // Clock Generation — 100 MHz (10 ns period)
    // ========================================================================

    initial begin
        clk = 0;
        forever #(CLK_PERIOD / 2) clk = ~clk;
    end

    // ========================================================================
    // Test Vector Storage
    // ========================================================================

    reg [63:0] stim_mem [0:MAX_STIM_WORDS-1];
    reg [63:0] exp_mem  [0:MAX_EXP_WORDS-1];

    // Fill data buffer for SRAM burst model (up to 16 u16 words for RGB565)
    /* verilator lint_off UNUSEDSIGNAL */
    reg [15:0] fill_buf [0:15];
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // SRAM Burst Responder
    //
    // When the DUT asserts sram_req, this task delivers burst data from
    // fill_buf and asserts sram_ack at the end.
    // ========================================================================

    /* verilator lint_off UNUSEDSIGNAL */
    task sram_respond;
        integer burst_len_int;
        integer w;
        begin
            // Wait for DUT to assert sram_req
            while (!sram_req) begin
                @(posedge clk);
            end

            burst_len_int = {24'b0, sram_burst_len};

            // Deliver burst data starting next cycle
            for (w = 0; w < burst_len_int; w = w + 1) begin
                @(negedge clk);
                sram_burst_data_valid = 1'b1;
                sram_burst_rdata      = fill_buf[w[3:0]];
                @(posedge clk);
                #1;
            end

            // Deassert data_valid, assert ack for 1 cycle
            @(negedge clk);
            sram_burst_data_valid = 1'b0;
            sram_burst_rdata      = 16'b0;
            sram_ack              = 1'b1;
            @(negedge clk);
            sram_ack              = 1'b0;
        end
    endtask
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // Check Helper
    // ========================================================================

    /* verilator lint_off UNUSEDSIGNAL */
    task check36(
        input string   name,
        input [35:0]   actual,
        input [35:0]   expected
    );
        begin
            if (actual === expected) begin
                pass_count = pass_count + 1;
            end else begin
                $display("FAIL: %s — expected %09h, got %09h", name, expected, actual);
                fail_count = fail_count + 1;
            end
        end
    endtask
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // Main Test Sequence
    // ========================================================================

    integer num_ops;
    integer num_lookups;
    integer stim_idx;
    integer exp_idx;
    integer op_num;
    integer lookup_num;
    integer j;

    // Unpacked header fields
    reg [7:0]  op_type;
    reg [23:0] hdr_base;
    reg [9:0]  hdr_px;
    reg [9:0]  hdr_py;
    reg [2:0]  hdr_fmt;
    reg [7:0]  hdr_wlog2;

    // Expected texel values
    reg [35:0] exp_t0;
    reg [35:0] exp_t1;
    reg [35:0] exp_t2;
    reg [35:0] exp_t3;

    initial begin
        $dumpfile("../build/sim_out/l1_cache_wrap_dt.fst");
        $dumpvars(0, tb_l1_cache_wrap_dt);

        // Load hex files
        $readmemh("../components/texture/detail/l1-cache/rtl/tests/vectors/l1_cache_wrap_stim.hex", stim_mem);
        $readmemh("../components/texture/detail/l1-cache/rtl/tests/vectors/l1_cache_wrap_exp.hex", exp_mem);

        // Initialize all inputs
        rst_n                = 0;
        lookup_req           = 0;
        pixel_x              = 10'b0;
        pixel_y              = 10'b0;
        tex_base_addr        = 24'b0;
        tex_format           = 3'b0;
        tex_width_log2       = 8'b0;
        invalidate           = 0;
        sram_burst_rdata     = 16'b0;
        sram_burst_data_valid = 0;
        sram_ack             = 0;
        sram_ready           = 1;

        // Reset sequence
        #100;
        @(negedge clk);
        rst_n = 1;
        @(posedge clk);
        @(posedge clk);

        // Read vector counts
        num_ops     = stim_mem[0][31:0];
        num_lookups = exp_mem[0][31:0];
        stim_idx    = 1;
        exp_idx     = 1;
        lookup_num  = 0;

        $display("=== L1 Cache WRAP Mode DT Test ===");
        $display("Operations: %0d (%0d lookups)", num_ops, num_lookups);

        for (op_num = 0; op_num < num_ops; op_num = op_num + 1) begin
            // Unpack header
            begin
                /* verilator lint_off UNUSEDSIGNAL */
                reg [63:0] hdr_word; // Bit [47] is reserved padding
                /* verilator lint_on UNUSEDSIGNAL */
                hdr_word  = stim_mem[stim_idx];
                op_type   = hdr_word[63:56];
                hdr_wlog2 = hdr_word[55:48];
                hdr_fmt   = hdr_word[46:44];
                hdr_py    = hdr_word[43:34];
                hdr_px    = hdr_word[33:24];
                hdr_base  = hdr_word[23:0];
            end
            stim_idx  = stim_idx + 1;

            if (op_type == 8'h00) begin
                // ── Fill operation ──────────────────────────────────

                // Load raw data into fill_buf (8 words of 64 bits = 16 u16)
                for (j = 0; j < 8; j = j + 1) begin
                    fill_buf[j * 2]     = stim_mem[stim_idx][15:0];
                    fill_buf[j * 2 + 1] = stim_mem[stim_idx][31:16];
                    stim_idx = stim_idx + 1;
                end

                // Wait for cache_ready
                while (!cache_ready) begin
                    @(posedge clk);
                end

                // Issue a lookup at the fill coordinates — this will miss
                // and trigger the fill FSM.
                @(negedge clk);
                lookup_req     = 1'b1;
                pixel_x        = hdr_px;
                pixel_y        = hdr_py;
                tex_base_addr  = hdr_base;
                tex_format     = hdr_fmt;
                tex_width_log2 = hdr_wlog2;

                @(negedge clk);
                lookup_req     = 1'b0;

                // Respond to the SRAM burst request
                sram_respond;

                // Wait for fill to complete and cache to return to idle
                while (!cache_ready) begin
                    @(posedge clk);
                end
                // Allow a settling cycle
                @(posedge clk);

            end else begin
                // ── Lookup operation ────────────────────────────────

                // Wait for cache_ready
                while (!cache_ready) begin
                    @(posedge clk);
                end

                // Issue lookup request on negedge
                @(negedge clk);
                lookup_req     = 1'b1;
                pixel_x        = hdr_px;
                pixel_y        = hdr_py;
                tex_base_addr  = hdr_base;
                tex_format     = hdr_fmt;
                tex_width_log2 = hdr_wlog2;

                @(negedge clk);
                lookup_req     = 1'b0;

                // Cycle 0 posedge: lookup_req registered, tag read started
                // Cycle 1 posedge: tag compare, cache_hit (combinational)
                //                  data_valid_r <= cache_hit (NBA)
                //                  bank read initiated on hit
                // Cycle 2 posedge: bank data ready, but data_valid_r
                //                  is cleared by this cycle's NBA.
                // Sample on negedge after cycle 1 to catch data_valid
                // while it's still high (before cycle 2's posedge clears it).
                @(posedge clk); // cycle 1 posedge
                @(negedge clk); // mid-cycle 1→2: data_valid stable

                if (!data_valid) begin
                    $display("FAIL: lookup %0d — expected hit but got miss (px=%0d, py=%0d)",
                             lookup_num, hdr_px, hdr_py);
                    fail_count = fail_count + 4;
                    // Skip expected values for this lookup
                    exp_idx    = exp_idx + 4;
                    lookup_num = lookup_num + 1;
                end else begin
                    // Read expected values
                    exp_t0 = exp_mem[exp_idx][35:0];
                    exp_t1 = exp_mem[exp_idx + 1][35:0];
                    exp_t2 = exp_mem[exp_idx + 2][35:0];
                    exp_t3 = exp_mem[exp_idx + 3][35:0];

                    // Compare bank outputs
                    check36($sformatf("lookup[%0d] bank0 (px=%0d,py=%0d)",
                                      lookup_num, hdr_px, hdr_py),
                            texel_out_0, exp_t0);
                    check36($sformatf("lookup[%0d] bank1 (px=%0d,py=%0d)",
                                      lookup_num, hdr_px, hdr_py),
                            texel_out_1, exp_t1);
                    check36($sformatf("lookup[%0d] bank2 (px=%0d,py=%0d)",
                                      lookup_num, hdr_px, hdr_py),
                            texel_out_2, exp_t2);
                    check36($sformatf("lookup[%0d] bank3 (px=%0d,py=%0d)",
                                      lookup_num, hdr_px, hdr_py),
                            texel_out_3, exp_t3);

                    exp_idx    = exp_idx + 4;
                    lookup_num = lookup_num + 1;
                end

                // Wait for pipeline to settle
                @(posedge clk);
            end
        end

        // ============================================================
        // Summary
        // ============================================================

        $display("");
        $display("tb_l1_cache_wrap_dt: %0d lookups, PASS=%0d FAIL=%0d",
                 lookup_num, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

    // Timeout watchdog
    initial begin
        #5000000;
        $display("\nERROR: Timeout — simulation ran too long");
        $finish;
    end

endmodule

`default_nettype wire
