// DT-verified testbench for texture_cache_l1 — MIRROR addressing mode
//
// Loads test vectors generated by gen_l1_cache_mirror_vectors (digital twin).
// For each vector:
//   FILL commands: simulate SRAM burst delivery to populate the cache
//   LOOKUP commands: assert lookup_req and compare texel outputs against DT
//
// Uses 100 MHz clk_core (10 ns period) matching the unified GPU clock domain.
// All DUT inputs driven on @(negedge clk) for setup time.

`default_nettype none

module tb_l1_cache_mirror_dt;

    // ========================================================================
    // Constants
    // ========================================================================

    localparam MAX_STIM_WORDS = 32768;
    localparam MAX_EXP_WORDS = 4096;

    // Command types (bits [63:62] of header word)
    localparam [1:0] CMD_FILL = 2'b00;

    // ========================================================================
    // Test Counters
    // ========================================================================

    integer pass_count = 0;
    integer fail_count = 0;
    integer lookup_idx = 0;

    // ========================================================================
    // DUT Signals
    // ========================================================================

    reg         clk;
    reg         rst_n;

    // Lookup request
    reg         lookup_req;
    reg  [9:0]  pixel_x;
    reg  [9:0]  pixel_y;
    reg  [23:0] tex_base_addr;
    reg  [2:0]  tex_format;
    reg  [7:0]  tex_width_log2;

    // Cache result
    wire        cache_hit;
    wire        data_valid;
    wire        cache_ready;
    wire [35:0] texel_out_0;
    wire [35:0] texel_out_1;
    wire [35:0] texel_out_2;
    wire [35:0] texel_out_3;

    // Invalidation
    reg         invalidate;

    // SRAM interface
    reg  [15:0] sram_burst_rdata;
    reg         sram_burst_data_valid;
    reg         sram_ack;
    reg         sram_ready;

    /* verilator lint_off UNUSEDSIGNAL */
    wire        fill_done;     // Connected but not checked in this testbench
    wire        sram_req;      // Monitored by sram_respond task
    wire [23:0] sram_addr;     // Not checked (twin provides burst data)
    wire [7:0]  sram_burst_len; // Not checked (twin provides burst length)
    wire        sram_we;       // Always 0 (read-only port)
    wire [31:0] sram_wdata;    // Always 0 (read-only port)
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // DUT Instantiation
    // ========================================================================

    texture_cache_l1 dut (
        .clk                  (clk),
        .rst_n                (rst_n),
        .lookup_req           (lookup_req),
        .pixel_x              (pixel_x),
        .pixel_y              (pixel_y),
        .tex_base_addr        (tex_base_addr),
        .tex_format           (tex_format),
        .tex_width_log2       (tex_width_log2),
        .cache_hit            (cache_hit),
        .data_valid           (data_valid),
        .cache_ready          (cache_ready),
        .fill_done            (fill_done),
        .texel_out_0          (texel_out_0),
        .texel_out_1          (texel_out_1),
        .texel_out_2          (texel_out_2),
        .texel_out_3          (texel_out_3),
        .invalidate           (invalidate),
        .sram_req             (sram_req),
        .sram_addr            (sram_addr),
        .sram_burst_len       (sram_burst_len),
        .sram_we              (sram_we),
        .sram_wdata           (sram_wdata),
        .sram_burst_rdata     (sram_burst_rdata),
        .sram_burst_data_valid(sram_burst_data_valid),
        .sram_ack             (sram_ack),
        .sram_ready           (sram_ready)
    );

    // ========================================================================
    // Clock Generation — 100 MHz (10 ns period)
    // ========================================================================

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    // ========================================================================
    // Test Vector Memory
    // ========================================================================

    reg [63:0] stim_mem [0:MAX_STIM_WORDS-1];
    reg [63:0] exp_mem  [0:MAX_EXP_WORDS-1];
    integer num_commands;
    integer num_lookups;

    // ========================================================================
    // SRAM Burst Data Storage (for FILL commands)
    // ========================================================================

    /* verilator lint_off UNUSEDSIGNAL */
    reg [15:0] fill_burst_data [0:31];
    /* verilator lint_on UNUSEDSIGNAL */
    reg [5:0]  fill_burst_len;

    // ========================================================================
    // Check Helper
    // ========================================================================

    /* verilator lint_off UNUSEDSIGNAL */
    task check36(input string name, input logic [35:0] actual, input logic [35:0] expected);
        if (actual === expected) begin
            pass_count = pass_count + 1;
        end else begin
            $display("FAIL: %s — expected %09h, got %09h", name, expected, actual);
            fail_count = fail_count + 1;
        end
    endtask
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // SRAM Response Task — delivers burst data when DUT requests it
    // ========================================================================
    //
    // Waits for sram_req, then delivers burst_len words of data.
    // Data comes from fill_burst_data[] which was loaded from the stim file.

    /* verilator lint_off UNUSEDSIGNAL */
    task sram_respond;
        integer w;
        // Wait for sram_req to assert
        while (!sram_req) begin
            @(posedge clk);
        end

        // Acknowledge after 1 cycle delay
        @(negedge clk);
        sram_ready = 1'b1;
        @(posedge clk);
        #1;

        // Deliver burst data words
        for (w = 0; w < {26'b0, fill_burst_len}; w = w + 1) begin
            @(negedge clk);
            sram_burst_data_valid = 1'b1;
            sram_burst_rdata      = fill_burst_data[w[4:0]];
            @(posedge clk);
            #1;
        end

        // Deassert data_valid and assert ack
        @(negedge clk);
        sram_burst_data_valid = 1'b0;
        sram_burst_rdata      = 16'b0;
        sram_ack              = 1'b1;
        @(posedge clk);
        #1;

        // Deassert ack
        @(negedge clk);
        sram_ack   = 1'b0;
        sram_ready = 1'b0;
    endtask
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // Main Test Sequence
    // ========================================================================

    integer cmd_idx;
    integer stim_ptr;
    integer exp_ptr;
    integer w;

    /* verilator lint_off UNUSEDSIGNAL */
    reg [63:0] header;
    /* verilator lint_on UNUSEDSIGNAL */
    reg [1:0]  cmd_type;
    reg [7:0]  cmd_tex_width_log2;
    reg [2:0]  cmd_tex_format;
    reg [23:0] cmd_tex_base_addr;
    reg [9:0]  cmd_pixel_y;
    reg [9:0]  cmd_pixel_x;

    initial begin
        $dumpfile("../build/sim_out/l1_cache_mirror_dt.vcd");
        $dumpvars(0, tb_l1_cache_mirror_dt);

        // Load test vectors
        $readmemh("../components/texture/detail/l1-cache/rtl/tests/vectors/l1_cache_mirror_stim.hex", stim_mem);
        $readmemh("../components/texture/detail/l1-cache/rtl/tests/vectors/l1_cache_mirror_exp.hex", exp_mem);

        num_commands = stim_mem[0][31:0];
        num_lookups  = exp_mem[0][31:0];

        // Initialize all inputs
        rst_n                 = 1'b0;
        lookup_req            = 1'b0;
        pixel_x               = 10'b0;
        pixel_y               = 10'b0;
        tex_base_addr         = 24'b0;
        tex_format            = 3'b0;
        tex_width_log2        = 8'b0;
        invalidate            = 1'b0;
        sram_burst_rdata      = 16'b0;
        sram_burst_data_valid = 1'b0;
        sram_ack              = 1'b0;
        sram_ready            = 1'b0;

        // Reset sequence
        #100;
        rst_n = 1'b1;
        @(posedge clk);
        @(posedge clk);

        $display("=== L1 Cache MIRROR Mode DT Test ===");
        $display("  %0d commands, %0d lookups", num_commands, num_lookups);

        stim_ptr   = 1; // Skip count word
        exp_ptr    = 1; // Skip count word
        lookup_idx = 0;

        for (cmd_idx = 0; cmd_idx < num_commands; cmd_idx = cmd_idx + 1) begin
            // Parse header word
            header             = stim_mem[stim_ptr];
            cmd_type           = stim_mem[stim_ptr][63:62];
            cmd_tex_width_log2 = stim_mem[stim_ptr][55:48];
            cmd_tex_format     = stim_mem[stim_ptr][47:45];
            cmd_tex_base_addr  = stim_mem[stim_ptr][44:21];
            cmd_pixel_y        = stim_mem[stim_ptr][20:11];
            cmd_pixel_x        = stim_mem[stim_ptr][10:1];
            stim_ptr           = stim_ptr + 1;

            if (cmd_type == CMD_FILL) begin
                // ── FILL command ──────────────────────────────────
                // Read burst length
                fill_burst_len = stim_mem[stim_ptr][5:0];
                stim_ptr       = stim_ptr + 1;

                // Read burst data
                for (w = 0; w < {26'b0, fill_burst_len}; w = w + 1) begin
                    fill_burst_data[w[4:0]] = stim_mem[stim_ptr][15:0];
                    stim_ptr                = stim_ptr + 1;
                end

                // Drive lookup to trigger a miss → fill
                // Wait for cache to be ready
                while (!cache_ready) begin
                    @(posedge clk);
                end

                @(negedge clk);
                lookup_req     = 1'b1;
                pixel_x        = cmd_pixel_x;
                pixel_y        = cmd_pixel_y;
                tex_base_addr  = cmd_tex_base_addr;
                tex_format     = cmd_tex_format;
                tex_width_log2 = cmd_tex_width_log2;

                @(posedge clk); // Cycle 0: lookup_req registered
                #1;

                @(negedge clk);
                lookup_req = 1'b0;

                @(posedge clk); // Cycle 1: tag compare → miss detected
                #1;

                // Now the fill FSM should start requesting SRAM data.
                // Respond to the SRAM request.
                sram_respond();

                // Wait for fill to complete (FILL_WRITE → FILL_IDLE)
                while (!cache_ready) begin
                    @(posedge clk);
                    #1;
                end

            end else begin
                // ── LOOKUP command ────────────────────────────────
                // Wait for cache to be ready
                while (!cache_ready) begin
                    @(posedge clk);
                end

                @(negedge clk);
                lookup_req     = 1'b1;
                pixel_x        = cmd_pixel_x;
                pixel_y        = cmd_pixel_y;
                tex_base_addr  = cmd_tex_base_addr;
                tex_format     = cmd_tex_format;
                tex_width_log2 = cmd_tex_width_log2;

                @(negedge clk);
                lookup_req = 1'b0;

                // Cycle 0 posedge: lookup_req registered, tag read started
                // Cycle 1 posedge: tag compare, cache_hit fires (combinational),
                //                  data_valid_r <= cache_hit (NBA),
                //                  bank read initiated on hit
                // Sample on negedge after cycle 1 to catch data_valid and
                // bank data while both are stable (before cycle 2 posedge
                // clears data_valid via NBA).
                @(posedge clk); // cycle 1 posedge
                @(negedge clk); // mid-cycle 1→2: data_valid and bank data stable

                if (!data_valid) begin
                    $display("FAIL: lookup %0d — expected hit, got miss (px=%0d, py=%0d)",
                             lookup_idx, cmd_pixel_x, cmd_pixel_y);
                    fail_count = fail_count + 1;

                    // Skip expected values for this lookup
                    exp_ptr = exp_ptr + 4;
                end else begin
                    pass_count = pass_count + 1;

                    // Compare texel outputs against expected
                    begin
                        reg [35:0] exp0, exp1, exp2, exp3;
                        exp0 = exp_mem[exp_ptr][35:0];
                        exp1 = exp_mem[exp_ptr + 1][35:0];
                        exp2 = exp_mem[exp_ptr + 2][35:0];
                        exp3 = exp_mem[exp_ptr + 3][35:0];
                        exp_ptr = exp_ptr + 4;

                        check36($sformatf("lookup[%0d] texel_out_0", lookup_idx),
                                texel_out_0, exp0);
                        check36($sformatf("lookup[%0d] texel_out_1", lookup_idx),
                                texel_out_1, exp1);
                        check36($sformatf("lookup[%0d] texel_out_2", lookup_idx),
                                texel_out_2, exp2);
                        check36($sformatf("lookup[%0d] texel_out_3", lookup_idx),
                                texel_out_3, exp3);
                    end
                end

                lookup_idx = lookup_idx + 1;
            end
        end

        // ============================================================
        // Summary
        // ============================================================
        $display("");
        $display("tb_l1_cache_mirror_dt: %0d lookups, PASS=%0d FAIL=%0d",
                 num_lookups, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

    // Timeout watchdog
    initial begin
        #5000000;
        $display("\nERROR: Timeout — simulation ran too long");
        $finish;
    end

endmodule

`default_nettype wire
