// DT-verified testbench for texture_block_decode
// Combinational: block words + texel indices + format -> 4 decoded texels
// Loads test vectors from hex files generated by the digital twin.
//
// See: UNIT-011.04 (Block Decompressor), INT-014, INT-032

module tb_block_decode_dt
    import fp_types_pkg::*;
;

    // ========================================================================
    // DUT signals (combinational — no clock needed)
    // ========================================================================

    reg [15:0] bw [0:31];     // Block words (convenience array)
    reg  [3:0] texel_idx_0;   // Texel index lane 0
    reg  [3:0] texel_idx_1;   // Texel index lane 1
    reg  [3:0] texel_idx_2;   // Texel index lane 2
    reg  [3:0] texel_idx_3;   // Texel index lane 3
    reg  [3:0] tex_format;    // Texture format code

    wire [35:0] texel_out_0;  // Decoded texel lane 0
    wire [35:0] texel_out_1;  // Decoded texel lane 1
    wire [35:0] texel_out_2;  // Decoded texel lane 2
    wire [35:0] texel_out_3;  // Decoded texel lane 3

    // ========================================================================
    // DUT instantiation
    // ========================================================================

    texture_block_decode dut (
        .block_word_0  (bw[0]),
        .block_word_1  (bw[1]),
        .block_word_2  (bw[2]),
        .block_word_3  (bw[3]),
        .block_word_4  (bw[4]),
        .block_word_5  (bw[5]),
        .block_word_6  (bw[6]),
        .block_word_7  (bw[7]),
        .block_word_8  (bw[8]),
        .block_word_9  (bw[9]),
        .block_word_10 (bw[10]),
        .block_word_11 (bw[11]),
        .block_word_12 (bw[12]),
        .block_word_13 (bw[13]),
        .block_word_14 (bw[14]),
        .block_word_15 (bw[15]),
        .block_word_16 (bw[16]),
        .block_word_17 (bw[17]),
        .block_word_18 (bw[18]),
        .block_word_19 (bw[19]),
        .block_word_20 (bw[20]),
        .block_word_21 (bw[21]),
        .block_word_22 (bw[22]),
        .block_word_23 (bw[23]),
        .block_word_24 (bw[24]),
        .block_word_25 (bw[25]),
        .block_word_26 (bw[26]),
        .block_word_27 (bw[27]),
        .block_word_28 (bw[28]),
        .block_word_29 (bw[29]),
        .block_word_30 (bw[30]),
        .block_word_31 (bw[31]),
        .texel_idx_0   (texel_idx_0),
        .texel_idx_1   (texel_idx_1),
        .texel_idx_2   (texel_idx_2),
        .texel_idx_3   (texel_idx_3),
        .tex_format    (tex_format),
        .texel_out_0   (texel_out_0),
        .texel_out_1   (texel_out_1),
        .texel_out_2   (texel_out_2),
        .texel_out_3   (texel_out_3)
    );

    // ========================================================================
    // Test vector storage
    // ========================================================================
    // Stimulus: 17 x 64-bit words per vector (control + 16 block-word pairs)
    // Expected: 4 x 64-bit words per vector (one per output lane)

    parameter MAX_VECTORS = 1024;
    parameter STIM_WORDS_PER_VEC = 17;
    parameter EXP_WORDS_PER_VEC = 4;

    reg [63:0] stim_mem [0:MAX_VECTORS*STIM_WORDS_PER_VEC];  // +1 for count header
    reg [63:0] exp_mem  [0:MAX_VECTORS*EXP_WORDS_PER_VEC];   // +1 for count header

    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    // ========================================================================
    // Format name helper for debug messages
    // ========================================================================

    /* verilator lint_off UNUSEDSIGNAL */
    function automatic string fmt_name(input logic [3:0] fmt);
        case (fmt)
            4'd0:    fmt_name = "BC1";
            4'd1:    fmt_name = "BC2";
            4'd2:    fmt_name = "BC3";
            4'd3:    fmt_name = "BC4";
            4'd4:    fmt_name = "RSVD";
            4'd5:    fmt_name = "RGB565";
            4'd6:    fmt_name = "RGBA8888";
            4'd7:    fmt_name = "R8";
            default: fmt_name = "UNKNOWN";
        endcase
    endfunction
    /* verilator lint_on UNUSEDSIGNAL */

    // ========================================================================
    // Main test sequence
    // ========================================================================

    initial begin
        $readmemh("../components/texture/detail/block-decoder/rtl/tests/vectors/block_decode_stim.hex", stim_mem);
        $readmemh("../components/texture/detail/block-decoder/rtl/tests/vectors/block_decode_exp.hex", exp_mem);

        // First entry in both files is the vector count
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            // Unpack stimulus: 17 words per vector, starting after the count header
            begin
                integer stim_base;
                integer w;
                reg [19:0] ctrl;

                stim_base = 1 + i * STIM_WORDS_PER_VEC;

                // Word 0: control (only low 20 bits used)
                ctrl = stim_mem[stim_base][19:0];
                texel_idx_0 = ctrl[3:0];
                texel_idx_1 = ctrl[7:4];
                texel_idx_2 = ctrl[11:8];
                texel_idx_3 = ctrl[15:12];
                tex_format  = ctrl[19:16];

                // Words 1-16: block word pairs
                // Each 64-bit word contains two 16-bit block words in low 32 bits:
                //   bits[15:0]  = block_word_{2*j}
                //   bits[31:16] = block_word_{2*j+1}
                for (w = 0; w < 16; w = w + 1) begin
                    bw[2*w]     = stim_mem[stim_base + 1 + w][15:0];
                    bw[2*w + 1] = stim_mem[stim_base + 1 + w][31:16];
                end
            end

            #1; // Allow combinational propagation

            // Compare all 4 output lanes against expected
            begin
                integer exp_base;
                reg [35:0] exp0;
                reg [35:0] exp1;
                reg [35:0] exp2;
                reg [35:0] exp3;
                integer lane_ok;

                exp_base = 1 + i * EXP_WORDS_PER_VEC;
                exp0 = exp_mem[exp_base][35:0];
                exp1 = exp_mem[exp_base + 1][35:0];
                exp2 = exp_mem[exp_base + 2][35:0];
                exp3 = exp_mem[exp_base + 3][35:0];

                lane_ok = 1;

                if (texel_out_0 !== exp0) begin
                    $display("FAIL [%0d] %s lane0: idx=%0d exp=%09h got=%09h",
                             i, fmt_name(tex_format), texel_idx_0, exp0, texel_out_0);
                    lane_ok = 0;
                end
                if (texel_out_1 !== exp1) begin
                    $display("FAIL [%0d] %s lane1: idx=%0d exp=%09h got=%09h",
                             i, fmt_name(tex_format), texel_idx_1, exp1, texel_out_1);
                    lane_ok = 0;
                end
                if (texel_out_2 !== exp2) begin
                    $display("FAIL [%0d] %s lane2: idx=%0d exp=%09h got=%09h",
                             i, fmt_name(tex_format), texel_idx_2, exp2, texel_out_2);
                    lane_ok = 0;
                end
                if (texel_out_3 !== exp3) begin
                    $display("FAIL [%0d] %s lane3: idx=%0d exp=%09h got=%09h",
                             i, fmt_name(tex_format), texel_idx_3, exp3, texel_out_3);
                    lane_ok = 0;
                end

                if (lane_ok == 1) begin
                    pass_count = pass_count + 1;
                end else begin
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_block_decode_dt: %0d vectors, PASS=%0d FAIL=%0d",
                 num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule
