// DT-verified testbench for texture_uv_coord
// Combinational: Q4.12 UV + config → wrapped tap coordinates + fractional weights
// Loads test vectors from hex files generated by the digital twin.

module tb_uv_coord_dt;

    // DUT signals (combinational — no clock needed for DUT)
    reg  [15:0] u_q412;       // U coordinate, Q4.12
    reg  [15:0] v_q412;       // V coordinate, Q4.12
    reg  [3:0]  width_log2;   // Texture width = 1 << width_log2
    reg  [3:0]  height_log2;  // Texture height = 1 << height_log2
    reg  [1:0]  u_wrap;       // U wrap mode
    reg  [1:0]  v_wrap;       // V wrap mode
    reg         is_bilinear;  // Bilinear filter enable

    wire [9:0]  tap0_x;       // Tap 0 wrapped texel X
    wire [9:0]  tap0_y;       // Tap 0 wrapped texel Y
    wire [9:0]  tap1_x;       // Tap 1 (tx+1, ty)
    wire [9:0]  tap1_y;
    wire [9:0]  tap2_x;       // Tap 2 (tx, ty+1)
    wire [9:0]  tap2_y;
    wire [9:0]  tap3_x;       // Tap 3 (tx+1, ty+1)
    wire [9:0]  tap3_y;
    wire [7:0]  frac_u;       // Sub-texel U fraction, UQ0.8
    wire [7:0]  frac_v;       // Sub-texel V fraction, UQ0.8

    // Instantiate DUT
    texture_uv_coord dut (
        .u_q412     (u_q412),
        .v_q412     (v_q412),
        .width_log2 (width_log2),
        .height_log2(height_log2),
        .u_wrap     (u_wrap),
        .v_wrap     (v_wrap),
        .is_bilinear(is_bilinear),
        .tap0_x     (tap0_x),
        .tap0_y     (tap0_y),
        .tap1_x     (tap1_x),
        .tap1_y     (tap1_y),
        .tap2_x     (tap2_x),
        .tap2_y     (tap2_y),
        .tap3_x     (tap3_x),
        .tap3_y     (tap3_y),
        .frac_u     (frac_u),
        .frac_v     (frac_v)
    );

    // Test vector storage
    // Stimulus: 1 × 64-bit word per vector
    // Expected: 2 × 64-bit words per vector
    parameter MAX_VECTORS = 2048;
    parameter EXP_WORDS_PER_VEC = 2;
    reg [63:0] stim_mem [0:MAX_VECTORS];
    reg [63:0] exp_mem  [0:MAX_VECTORS*EXP_WORDS_PER_VEC];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    /* verilator lint_off UNUSEDSIGNAL */
    initial begin
        $readmemh("../components/texture/detail/uv-coord/rtl/tests/vectors/uv_coord_stim.hex", stim_mem);
        $readmemh("../components/texture/detail/uv-coord/rtl/tests/vectors/uv_coord_exp.hex", exp_mem);

        // First entry is the vector count
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            // Unpack stimulus: 1 word per vector
            // [63:48] = u_q412, [47:32] = v_q412
            // [31:28] = width_log2, [27:24] = height_log2
            // [23:22] = u_wrap, [21:20] = v_wrap
            // [19] = is_bilinear, [18:0] = reserved
            begin
                reg [63:0] stim_word;
                stim_word   = stim_mem[1 + i];

                u_q412      = stim_word[63:48];
                v_q412      = stim_word[47:32];
                width_log2  = stim_word[31:28];
                height_log2 = stim_word[27:24];
                u_wrap      = stim_word[23:22];
                v_wrap      = stim_word[21:20];
                is_bilinear = stim_word[19];
            end

            #1; // Allow combinational propagation

            // Unpack expected: 2 words per vector
            begin
                integer exp_base;
                reg [63:0] exp_w0;
                reg [63:0] exp_w1;
                reg [9:0]  exp_tap0_x, exp_tap0_y;
                reg [9:0]  exp_tap1_x, exp_tap1_y;
                reg [9:0]  exp_tap2_x, exp_tap2_y;
                reg [9:0]  exp_tap3_x, exp_tap3_y;
                reg [7:0]  exp_frac_u, exp_frac_v;
                reg        mismatch;

                exp_base = 1 + i * EXP_WORDS_PER_VEC;
                exp_w0 = exp_mem[exp_base];
                exp_w1 = exp_mem[exp_base + 1];

                // Word 0: [59:50]=tap0_x [49:40]=tap0_y [39:30]=tap1_x
                //         [29:20]=tap1_y [19:10]=tap2_x [9:0]=tap2_y
                exp_tap0_x = exp_w0[59:50];
                exp_tap0_y = exp_w0[49:40];
                exp_tap1_x = exp_w0[39:30];
                exp_tap1_y = exp_w0[29:20];
                exp_tap2_x = exp_w0[19:10];
                exp_tap2_y = exp_w0[9:0];

                // Word 1: [35:26]=tap3_x [25:16]=tap3_y [15:8]=frac_u [7:0]=frac_v
                exp_tap3_x = exp_w1[35:26];
                exp_tap3_y = exp_w1[25:16];
                exp_frac_u = exp_w1[15:8];
                exp_frac_v = exp_w1[7:0];

                mismatch = 1'b0;

                // Always compare tap0
                if (tap0_x !== exp_tap0_x || tap0_y !== exp_tap0_y) begin
                    mismatch = 1'b1;
                end

                // For bilinear mode, also compare tap1-3 and fracs
                if (is_bilinear) begin
                    if (tap1_x !== exp_tap1_x || tap1_y !== exp_tap1_y) begin
                        mismatch = 1'b1;
                    end
                    if (tap2_x !== exp_tap2_x || tap2_y !== exp_tap2_y) begin
                        mismatch = 1'b1;
                    end
                    if (tap3_x !== exp_tap3_x || tap3_y !== exp_tap3_y) begin
                        mismatch = 1'b1;
                    end
                    if (frac_u !== exp_frac_u || frac_v !== exp_frac_v) begin
                        mismatch = 1'b1;
                    end
                end

                if (!mismatch) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: u=%04h v=%04h wlog2=%0d hlog2=%0d uwrap=%0d vwrap=%0d bil=%0b",
                             i, u_q412, v_q412, width_log2, height_log2,
                             u_wrap, v_wrap, is_bilinear);
                    $display("  tap0: exp=(%0d,%0d) got=(%0d,%0d)",
                             exp_tap0_x, exp_tap0_y, tap0_x, tap0_y);
                    if (is_bilinear) begin
                        $display("  tap1: exp=(%0d,%0d) got=(%0d,%0d)",
                                 exp_tap1_x, exp_tap1_y, tap1_x, tap1_y);
                        $display("  tap2: exp=(%0d,%0d) got=(%0d,%0d)",
                                 exp_tap2_x, exp_tap2_y, tap2_x, tap2_y);
                        $display("  tap3: exp=(%0d,%0d) got=(%0d,%0d)",
                                 exp_tap3_x, exp_tap3_y, tap3_x, tap3_y);
                        $display("  frac: exp=(%02h,%02h) got=(%02h,%02h)",
                                 exp_frac_u, exp_frac_v, frac_u, frac_v);
                    end
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_uv_coord_dt: %0d vectors, PASS=%0d FAIL=%0d",
                 num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end
    /* verilator lint_on UNUSEDSIGNAL */

endmodule
