// Spec-ref: unit_011.01_uv_coordinate_processing.md
//
// DT-verified testbench for texture_uv_coord (INDEXED8_2X2 NEAREST).
// Combinational: Q4.12 UV + config -> half-resolution index-cache
// address (u_idx, v_idx) + quadrant selector.
// Loads test vectors from hex files generated by the digital twin
// (`gen_uv_coord_vectors`).

module tb_uv_coord_dt;

    // DUT signals (combinational -- no clock needed for DUT)
    reg  [15:0] uv_q412_u;
    reg  [15:0] uv_q412_v;
    reg  [3:0]  tex_width_log2;
    reg  [3:0]  tex_height_log2;
    reg  [1:0]  tex_u_wrap;
    reg  [1:0]  tex_v_wrap;

    wire [9:0]  u_idx;
    wire [9:0]  v_idx;
    wire [1:0]  quadrant;

    // Instantiate DUT
    texture_uv_coord dut (
        .uv_q412_u       (uv_q412_u),
        .uv_q412_v       (uv_q412_v),
        .tex_width_log2  (tex_width_log2),
        .tex_height_log2 (tex_height_log2),
        .tex_u_wrap      (tex_u_wrap),
        .tex_v_wrap      (tex_v_wrap),
        .u_idx           (u_idx),
        .v_idx           (v_idx),
        .quadrant        (quadrant)
    );

    // Test vector storage
    // Stimulus: 1 x 64-bit word per vector
    // Expected: 1 x 64-bit word per vector
    parameter MAX_VECTORS = 2048;
    reg [63:0] stim_mem [0:MAX_VECTORS];
    reg [63:0] exp_mem  [0:MAX_VECTORS];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    /* verilator lint_off UNUSEDSIGNAL */
    initial begin
        $readmemh("../rtl/components/texture/detail/uv-coord/tests/vectors/uv_coord_stim.hex", stim_mem);
        $readmemh("../rtl/components/texture/detail/uv-coord/tests/vectors/uv_coord_exp.hex", exp_mem);

        // First entry is the vector count
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            // Unpack stimulus: 1 word per vector
            // [63:48] = u_q412, [47:32] = v_q412
            // [31:28] = width_log2, [27:24] = height_log2
            // [23:22] = u_wrap, [21:20] = v_wrap
            // [19:0]  = reserved (zero)
            begin
                reg [63:0] stim_word;
                stim_word        = stim_mem[1 + i];

                uv_q412_u        = stim_word[63:48];
                uv_q412_v        = stim_word[47:32];
                tex_width_log2   = stim_word[31:28];
                tex_height_log2  = stim_word[27:24];
                tex_u_wrap       = stim_word[23:22];
                tex_v_wrap       = stim_word[21:20];
            end

            #1; // Allow combinational propagation

            // Unpack expected: 1 word per vector
            // [63:32] = reserved (zero)
            // [31:22] = u_idx (10-bit)
            // [21:12] = v_idx (10-bit)
            // [11:10] = quadrant (2-bit)
            // [9:0]   = reserved (zero)
            begin
                reg [63:0] exp_w0;
                reg [9:0]  exp_u_idx;
                reg [9:0]  exp_v_idx;
                reg [1:0]  exp_quadrant;
                reg        mismatch;

                exp_w0 = exp_mem[1 + i];

                exp_u_idx    = exp_w0[31:22];
                exp_v_idx    = exp_w0[21:12];
                exp_quadrant = exp_w0[11:10];

                mismatch = 1'b0;

                if (u_idx !== exp_u_idx || v_idx !== exp_v_idx) begin
                    mismatch = 1'b1;
                end

                if (quadrant !== exp_quadrant) begin
                    mismatch = 1'b1;
                end

                if (!mismatch) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: u=%04h v=%04h wlog2=%0d hlog2=%0d uwrap=%0d vwrap=%0d",
                             i, uv_q412_u, uv_q412_v, tex_width_log2, tex_height_log2,
                             tex_u_wrap, tex_v_wrap);
                    $display("  idx : exp=(%0d,%0d) got=(%0d,%0d)",
                             exp_u_idx, exp_v_idx, u_idx, v_idx);
                    $display("  quad: exp=%0d got=%0d",
                             exp_quadrant, quadrant);
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_uv_coord_dt: %0d vectors, PASS=%0d FAIL=%0d",
                 num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end
    /* verilator lint_on UNUSEDSIGNAL */

endmodule
