// DT-verified testbench for texture_uv_coord (NEAREST-only).
// Combinational: Q4.12 UV + config -> wrapped tap coordinates + sub-texel position.
// Loads test vectors from hex files generated by the digital twin.

module tb_uv_coord_dt;

    // DUT signals (combinational -- no clock needed for DUT)
    reg  [15:0] u_q412;       // U coordinate, Q4.12
    reg  [15:0] v_q412;       // V coordinate, Q4.12
    reg  [3:0]  width_log2;   // Texture width = 1 << width_log2
    reg  [3:0]  height_log2;  // Texture height = 1 << height_log2
    reg  [1:0]  u_wrap;       // U wrap mode
    reg  [1:0]  v_wrap;       // V wrap mode

    wire [9:0]  tap0_x;       // Wrapped texel X (NEAREST tap)
    wire [9:0]  tap0_y;       // Wrapped texel Y (NEAREST tap)
    wire [1:0]  sub_u;        // Sub-texel column within 4x4 block
    wire [1:0]  sub_v;        // Sub-texel row within 4x4 block

    // Instantiate DUT
    texture_uv_coord dut (
        .u_q412     (u_q412),
        .v_q412     (v_q412),
        .width_log2 (width_log2),
        .height_log2(height_log2),
        .u_wrap     (u_wrap),
        .v_wrap     (v_wrap),
        .tap0_x     (tap0_x),
        .tap0_y     (tap0_y),
        .sub_u      (sub_u),
        .sub_v      (sub_v)
    );

    // Test vector storage
    // Stimulus: 1 x 64-bit word per vector
    // Expected: 1 x 64-bit word per vector
    parameter MAX_VECTORS = 2048;
    reg [63:0] stim_mem [0:MAX_VECTORS];
    reg [63:0] exp_mem  [0:MAX_VECTORS];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    /* verilator lint_off UNUSEDSIGNAL */
    initial begin
        $readmemh("../rtl/components/texture/detail/uv-coord/tests/vectors/uv_coord_stim.hex", stim_mem);
        $readmemh("../rtl/components/texture/detail/uv-coord/tests/vectors/uv_coord_exp.hex", exp_mem);

        // First entry is the vector count
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            // Unpack stimulus: 1 word per vector
            // [63:48] = u_q412, [47:32] = v_q412
            // [31:28] = width_log2, [27:24] = height_log2
            // [23:22] = u_wrap, [21:20] = v_wrap
            // [19:0]  = reserved (zero)
            begin
                reg [63:0] stim_word;
                stim_word   = stim_mem[1 + i];

                u_q412      = stim_word[63:48];
                v_q412      = stim_word[47:32];
                width_log2  = stim_word[31:28];
                height_log2 = stim_word[27:24];
                u_wrap      = stim_word[23:22];
                v_wrap      = stim_word[21:20];
            end

            #1; // Allow combinational propagation

            // Unpack expected: 1 word per vector
            // [19:10] = tap_x (10-bit)
            // [9:0]   = tap_y (10-bit)
            begin
                reg [63:0] exp_w0;
                reg [9:0]  exp_tap0_x;
                reg [9:0]  exp_tap0_y;
                reg [1:0]  exp_sub_u;
                reg [1:0]  exp_sub_v;
                reg        mismatch;

                exp_w0 = exp_mem[1 + i];

                exp_tap0_x = exp_w0[19:10];
                exp_tap0_y = exp_w0[9:0];

                // Sub-texel position is the low 2 bits of the tap coordinate
                exp_sub_u = exp_tap0_x[1:0];
                exp_sub_v = exp_tap0_y[1:0];

                mismatch = 1'b0;

                if (tap0_x !== exp_tap0_x || tap0_y !== exp_tap0_y) begin
                    mismatch = 1'b1;
                end

                if (sub_u !== exp_sub_u || sub_v !== exp_sub_v) begin
                    mismatch = 1'b1;
                end

                if (!mismatch) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: u=%04h v=%04h wlog2=%0d hlog2=%0d uwrap=%0d vwrap=%0d",
                             i, u_q412, v_q412, width_log2, height_log2,
                             u_wrap, v_wrap);
                    $display("  tap0: exp=(%0d,%0d) got=(%0d,%0d)",
                             exp_tap0_x, exp_tap0_y, tap0_x, tap0_y);
                    $display("  sub : exp=(%0d,%0d) got=(%0d,%0d)",
                             exp_sub_u, exp_sub_v, sub_u, sub_v);
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_uv_coord_dt: %0d vectors, PASS=%0d FAIL=%0d",
                 num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end
    /* verilator lint_on UNUSEDSIGNAL */

endmodule
