// DT-verified testbench for texture_bilinear
// Combinational: 4 × UQ1.8 texels + frac_u/frac_v → blended UQ1.8 texel
// Loads test vectors from hex files generated by the digital twin.

`timescale 1ns/1ps

module tb_texture_bilinear_dt;

    // DUT signals (combinational — no clock needed for DUT)
    reg  [7:0]  frac_u;
    reg  [7:0]  frac_v;
    reg         is_bilinear;
    reg  [35:0] texel_tap0;
    reg  [35:0] texel_tap1;
    reg  [35:0] texel_tap2;
    reg  [35:0] texel_tap3;
    wire [35:0] texel_out;

    // Instantiate DUT
    texture_bilinear dut (
        .frac_u     (frac_u),
        .frac_v     (frac_v),
        .is_bilinear(is_bilinear),
        .texel_tap0 (texel_tap0),
        .texel_tap1 (texel_tap1),
        .texel_tap2 (texel_tap2),
        .texel_tap3 (texel_tap3),
        .texel_out  (texel_out)
    );

    // Test vector storage
    // Stimulus: 5 × 64-bit words per vector (ctrl + 4 texels)
    // Expected: 1 × 64-bit word per vector
    parameter MAX_VECTORS = 1024;
    parameter WORDS_PER_VEC = 5;
    reg [63:0] stim_mem [0:MAX_VECTORS*WORDS_PER_VEC];
    reg [63:0] exp_mem  [0:MAX_VECTORS];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    initial begin
        $readmemh("../rtl/components/texture/detail/bilinear-filter/tests/vectors/bilinear_stim.hex", stim_mem);
        $readmemh("../rtl/components/texture/detail/bilinear-filter/tests/vectors/bilinear_exp.hex", exp_mem);

        // First entry is the vector count
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            // Unpack stimulus: 5 words per vector
            // Word 0: {47'b0, is_bilinear[16], frac_u[15:8], frac_v[7:0]}
            // Words 1-4: {28'b0, texel_tapN[35:0]}
            begin
                integer base;
                base = 1 + i * WORDS_PER_VEC;

                is_bilinear = stim_mem[base][16];
                frac_u      = stim_mem[base][15:8];
                frac_v      = stim_mem[base][7:0];
                texel_tap0  = stim_mem[base + 1][35:0];
                texel_tap1  = stim_mem[base + 2][35:0];
                texel_tap2  = stim_mem[base + 3][35:0];
                texel_tap3  = stim_mem[base + 4][35:0];
            end

            #1; // Allow combinational propagation

            begin
                reg [35:0] exp_out;
                exp_out = exp_mem[i + 1][35:0];

                if (texel_out === exp_out) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: fu=%02h fv=%02h bil=%0b tap0=%09h tap1=%09h tap2=%09h tap3=%09h exp=%09h got=%09h",
                             i, frac_u, frac_v, is_bilinear,
                             texel_tap0, texel_tap1, texel_tap2, texel_tap3,
                             exp_out, texel_out);
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_texture_bilinear_dt: %0d vectors, PASS=%0d FAIL=%0d",
                 num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule
