// DT-verified testbench for color_combiner
// 4-stage pipeline: drives one vector at a time, waits for output, compares.
// Loads test vectors from hex files generated by the digital twin.

`default_nettype none

module tb_cc_dt;

    // ====================================================================
    // Clock and reset
    // ====================================================================
    reg         clk;              // System clock, 10ns period
    reg         rst_n;            // Active-low synchronous reset

    initial begin
        clk = 1'b0;
        forever begin
            #5 clk = ~clk;
        end
    end

    // ====================================================================
    // DUT signals
    // ====================================================================
    reg  [63:0] tex_color0;       // Q4.12 RGBA packed
    reg  [63:0] tex_color1;       // Q4.12 RGBA packed
    reg  [63:0] shade0;           // Q4.12 RGBA packed
    reg  [63:0] shade1;           // Q4.12 RGBA packed
    reg  [15:0] frag_x;           // Fragment X coordinate
    reg  [15:0] frag_y;           // Fragment Y coordinate
    reg  [15:0] frag_z;           // Fragment Z depth
    reg         frag_valid;       // Fragment valid
    reg  [63:0] cc_mode;          // Combiner mode config
    reg  [63:0] const_color;      // Constant colors RGBA8888

    wire [63:0] combined_color;   // Q4.12 RGBA output
    wire        out_frag_valid;   // Output valid

    /* verilator lint_off UNUSEDSIGNAL */
    wire [15:0] out_frag_x;       // Passthrough X (unused in TB)
    wire [15:0] out_frag_y;       // Passthrough Y (unused in TB)
    wire [15:0] out_frag_z;       // Passthrough Z (unused in TB)
    wire        in_ready;         // Backpressure signal (unused in TB)
    /* verilator lint_on UNUSEDSIGNAL */

    reg         out_ready;        // Downstream ready (always 1)

    // ====================================================================
    // DUT instantiation
    // ====================================================================
    color_combiner dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .tex_color0     (tex_color0),
        .tex_color1     (tex_color1),
        .shade0         (shade0),
        .shade1         (shade1),
        .frag_x         (frag_x),
        .frag_y         (frag_y),
        .frag_z         (frag_z),
        .frag_valid     (frag_valid),
        .cc_mode        (cc_mode),
        .const_color    (const_color),
        .combined_color (combined_color),
        .out_frag_x     (out_frag_x),
        .out_frag_y     (out_frag_y),
        .out_frag_z     (out_frag_z),
        .out_frag_valid (out_frag_valid),
        .in_ready       (in_ready),
        .out_ready      (out_ready)
    );

    // ====================================================================
    // Test vector storage
    // ====================================================================
    parameter MAX_VECTORS   = 512;                         // Max supported vectors
    parameter WORDS_PER_VEC = 7;                           // 7 x 64-bit words per stimulus vector

    reg [63:0] stim_mem [0:MAX_VECTORS*WORDS_PER_VEC];    // Stimulus memory
    reg [63:0] exp_mem  [0:MAX_VECTORS];                   // Expected output memory

    integer num_vectors;   // Vector count from file header
    integer pass_count;    // Passing comparisons
    integer fail_count;    // Failing comparisons

    // ====================================================================
    // Main test sequence
    // ====================================================================
    initial begin
        // Initialise counters and inputs
        pass_count  = 0;
        fail_count  = 0;
        rst_n       = 1'b0;
        frag_valid  = 1'b0;
        out_ready   = 1'b1;
        tex_color0  = 64'd0;
        tex_color1  = 64'd0;
        shade0      = 64'd0;
        shade1      = 64'd0;
        frag_x      = 16'd0;
        frag_y      = 16'd0;
        frag_z      = 16'd0;
        cc_mode     = 64'd0;
        const_color = 64'd0;

        // Load hex test vectors
        $readmemh("../components/color-combiner/rtl/tests/vectors/cc_stim.hex", stim_mem);
        $readmemh("../components/color-combiner/rtl/tests/vectors/cc_exp.hex", exp_mem);

        // First word is vector count
        num_vectors = stim_mem[0][31:0];

        // Release reset
        #20;
        rst_n = 1'b1;
        @(negedge clk);

        // Drive each vector one at a time and wait for pipeline drain
        for (int i = 0; i < num_vectors; i++) begin
            begin
                integer base;              // Base index into stim_mem
                /* verilator lint_off UNUSEDSIGNAL */
                reg [63:0] ctrl_word;      // Control word with fragment coords
                /* verilator lint_on UNUSEDSIGNAL */

                base = 1 + i * WORDS_PER_VEC;

                // Unpack 7 stimulus words
                cc_mode     = stim_mem[base];
                const_color = stim_mem[base + 1];
                tex_color0  = stim_mem[base + 2];
                tex_color1  = stim_mem[base + 3];
                shade0      = stim_mem[base + 4];
                shade1      = stim_mem[base + 5];
                ctrl_word   = stim_mem[base + 6];
                frag_x      = ctrl_word[47:32];
                frag_y      = ctrl_word[31:16];
                frag_z      = ctrl_word[15:0];
            end

            // Assert valid for exactly one cycle
            frag_valid = 1'b1;
            @(negedge clk);
            frag_valid = 1'b0;

            // Wait for output valid (pipeline latency = 4 cycles)
            // Poll posedge until out_frag_valid is asserted
            begin
                integer wait_cycles;
                wait_cycles = 0;
                while (!out_frag_valid && wait_cycles < 20) begin
                    @(posedge clk);
                    wait_cycles = wait_cycles + 1;
                end
            end

            // Compare output
            begin
                reg [63:0] exp_color;      // Expected combined color
                exp_color = exp_mem[i + 1];

                if (combined_color === exp_color) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: cc_mode=%016h const=%016h tc0=%016h tc1=%016h sh0=%016h sh1=%016h exp=%016h got=%016h",
                             i, cc_mode, const_color, tex_color0, tex_color1,
                             shade0, shade1, exp_color, combined_color);
                    fail_count = fail_count + 1;
                end
            end

            // Return to negedge for next vector drive
            @(negedge clk);
        end

        // Summary
        $display("");
        $display("tb_cc_dt: %0d vectors, PASS=%0d FAIL=%0d",
                 num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule

`default_nettype wire
