// DT-verified testbench for raster_attr_accum
// Loads derivatives, initial values, command sequences, and expected promoted
// outputs from hex files generated by the digital twin.
// Verification: UNIT-005.03 (Attribute Accumulation)

`timescale 1ns/1ps

module tb_attr_accum_dt;

    // Clock and reset
    /* verilator lint_off PROCASSINIT */
    reg clk = 1'b0;
    /* verilator lint_on PROCASSINIT */
    reg rst_n;
    always #5 clk = ~clk;

    // Control signals
    reg latch_derivs;
    reg step_x;
    reg step_y;
    reg tile_col_step;
    reg tile_row_step;

    // Derivative inputs (28 × 32-bit: 14 dx + 14 dy)
    reg signed [31:0] pre_c0r_dx, pre_c0r_dy;
    reg signed [31:0] pre_c0g_dx, pre_c0g_dy;
    reg signed [31:0] pre_c0b_dx, pre_c0b_dy;
    reg signed [31:0] pre_c0a_dx, pre_c0a_dy;
    reg signed [31:0] pre_c1r_dx, pre_c1r_dy;
    reg signed [31:0] pre_c1g_dx, pre_c1g_dy;
    reg signed [31:0] pre_c1b_dx, pre_c1b_dy;
    reg signed [31:0] pre_c1a_dx, pre_c1a_dy;
    reg signed [31:0] pre_z_dx, pre_z_dy;
    reg signed [31:0] pre_s0_dx, pre_s0_dy;
    reg signed [31:0] pre_t0_dx, pre_t0_dy;
    reg signed [31:0] pre_s1_dx, pre_s1_dy;
    reg signed [31:0] pre_t1_dx, pre_t1_dy;
    reg signed [31:0] pre_q_dx, pre_q_dy;

    // Initial value inputs (14 × 32-bit)
    reg signed [31:0] init_c0r, init_c0g, init_c0b, init_c0a;
    reg signed [31:0] init_c1r, init_c1g, init_c1b, init_c1a;
    reg signed [31:0] init_z;
    reg signed [31:0] init_s0, init_t0, init_s1, init_t1;
    reg signed [31:0] init_q;

    // Promoted outputs
    wire [15:0] out_c0r, out_c0g, out_c0b, out_c0a;
    wire [15:0] out_c1r, out_c1g, out_c1b, out_c1a;
    wire [15:0] out_z;
    wire signed [31:0] s0_acc_out, t0_acc_out, s1_acc_out, t1_acc_out, q_acc_out;

    // DUT instantiation
    raster_attr_accum dut (
        .clk(clk), .rst_n(rst_n),
        .latch_derivs(latch_derivs), .step_x(step_x), .step_y(step_y),
        .tile_col_step(tile_col_step), .tile_row_step(tile_row_step),
        .pre_c0r_dx(pre_c0r_dx), .pre_c0r_dy(pre_c0r_dy),
        .pre_c0g_dx(pre_c0g_dx), .pre_c0g_dy(pre_c0g_dy),
        .pre_c0b_dx(pre_c0b_dx), .pre_c0b_dy(pre_c0b_dy),
        .pre_c0a_dx(pre_c0a_dx), .pre_c0a_dy(pre_c0a_dy),
        .pre_c1r_dx(pre_c1r_dx), .pre_c1r_dy(pre_c1r_dy),
        .pre_c1g_dx(pre_c1g_dx), .pre_c1g_dy(pre_c1g_dy),
        .pre_c1b_dx(pre_c1b_dx), .pre_c1b_dy(pre_c1b_dy),
        .pre_c1a_dx(pre_c1a_dx), .pre_c1a_dy(pre_c1a_dy),
        .pre_z_dx(pre_z_dx), .pre_z_dy(pre_z_dy),
        .pre_s0_dx(pre_s0_dx), .pre_s0_dy(pre_s0_dy),
        .pre_t0_dx(pre_t0_dx), .pre_t0_dy(pre_t0_dy),
        .pre_s1_dx(pre_s1_dx), .pre_s1_dy(pre_s1_dy),
        .pre_t1_dx(pre_t1_dx), .pre_t1_dy(pre_t1_dy),
        .pre_q_dx(pre_q_dx), .pre_q_dy(pre_q_dy),
        .init_c0r(init_c0r), .init_c0g(init_c0g), .init_c0b(init_c0b), .init_c0a(init_c0a),
        .init_c1r(init_c1r), .init_c1g(init_c1g), .init_c1b(init_c1b), .init_c1a(init_c1a),
        .init_z(init_z),
        .init_s0(init_s0), .init_t0(init_t0),
        .init_s1(init_s1), .init_t1(init_t1),
        .init_q(init_q),
        .out_c0r(out_c0r), .out_c0g(out_c0g), .out_c0b(out_c0b), .out_c0a(out_c0a),
        .out_c1r(out_c1r), .out_c1g(out_c1g), .out_c1b(out_c1b), .out_c1a(out_c1a),
        .out_z(out_z),
        .s0_acc_out(s0_acc_out), .t0_acc_out(t0_acc_out),
        .s1_acc_out(s1_acc_out), .t1_acc_out(t1_acc_out),
        .q_acc_out(q_acc_out)
    );

    // Hex storage
    parameter MAX_STIM_WORDS = 2048;
    parameter MAX_EXP_WORDS = 4096;
    reg [31:0] stim_mem [0:MAX_STIM_WORDS-1];
    /* verilator lint_off UNUSEDSIGNAL */
    reg [31:0] exp_mem  [0:MAX_EXP_WORDS-1];
    /* verilator lint_on UNUSEDSIGNAL */

    integer pass_count = 0;
    integer fail_count = 0;

    task check16(input string name, input [15:0] actual, input [15:0] expected);
        if (actual === expected) begin
            pass_count = pass_count + 1;
        end else begin
            $display("    FAIL: %s expected=0x%04x got=0x%04x", name, expected, actual);
            fail_count = fail_count + 1;
        end
    endtask

    task check32(input string name, input [31:0] actual, input [31:0] expected);
        if (actual === expected) begin
            pass_count = pass_count + 1;
        end else begin
            $display("    FAIL: %s expected=0x%08x got=0x%08x", name, expected, actual);
            fail_count = fail_count + 1;
        end
    endtask

    // Clear all control signals
    task clear_controls;
        latch_derivs = 0;
        step_x = 0;
        step_y = 0;
        tile_col_step = 0;
        tile_row_step = 0;
    endtask

    integer si;  // Stimulus index
    integer ei;  // Expected index
    integer seq_idx;
    integer cmd_count;
    integer cmd_idx;

    initial begin
        $readmemh("../components/rasterizer/rtl/tests/vectors/attr_accum_stim.hex", stim_mem);
        $readmemh("../components/rasterizer/rtl/tests/vectors/attr_accum_exp.hex", exp_mem);

        rst_n = 0;
        clear_controls();
        repeat (4) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        si = 0;
        ei = 0;

        // Process each test sequence
        for (seq_idx = 0; seq_idx < 16; seq_idx = seq_idx + 1) begin
            if (stim_mem[si] === 32'hxxxxxxxx) begin
                seq_idx = 16; // Break
            end else begin
                $display("Sequence %0d: loading derivatives and init values...", seq_idx);

                // Load 14 dx derivatives
                pre_c0r_dx = stim_mem[si+ 0]; pre_c0g_dx = stim_mem[si+ 1];
                pre_c0b_dx = stim_mem[si+ 2]; pre_c0a_dx = stim_mem[si+ 3];
                pre_c1r_dx = stim_mem[si+ 4]; pre_c1g_dx = stim_mem[si+ 5];
                pre_c1b_dx = stim_mem[si+ 6]; pre_c1a_dx = stim_mem[si+ 7];
                pre_z_dx   = stim_mem[si+ 8]; pre_s0_dx  = stim_mem[si+ 9];
                pre_t0_dx  = stim_mem[si+10]; pre_q_dx   = stim_mem[si+11];
                pre_s1_dx  = stim_mem[si+12]; pre_t1_dx  = stim_mem[si+13];

                // Load 14 dy derivatives
                pre_c0r_dy = stim_mem[si+14]; pre_c0g_dy = stim_mem[si+15];
                pre_c0b_dy = stim_mem[si+16]; pre_c0a_dy = stim_mem[si+17];
                pre_c1r_dy = stim_mem[si+18]; pre_c1g_dy = stim_mem[si+19];
                pre_c1b_dy = stim_mem[si+20]; pre_c1a_dy = stim_mem[si+21];
                pre_z_dy   = stim_mem[si+22]; pre_s0_dy  = stim_mem[si+23];
                pre_t0_dy  = stim_mem[si+24]; pre_q_dy   = stim_mem[si+25];
                pre_s1_dy  = stim_mem[si+26]; pre_t1_dy  = stim_mem[si+27];

                // Load 14 init values
                init_c0r = stim_mem[si+28]; init_c0g = stim_mem[si+29];
                init_c0b = stim_mem[si+30]; init_c0a = stim_mem[si+31];
                init_c1r = stim_mem[si+32]; init_c1g = stim_mem[si+33];
                init_c1b = stim_mem[si+34]; init_c1a = stim_mem[si+35];
                init_z   = stim_mem[si+36]; init_s0  = stim_mem[si+37];
                init_t0  = stim_mem[si+38]; init_q   = stim_mem[si+39];
                init_s1  = stim_mem[si+40]; init_t1  = stim_mem[si+41];

                si = si + 42;

                // Command count
                cmd_count = stim_mem[si];
                si = si + 1;

                // Execute command sequence
                for (cmd_idx = 0; cmd_idx < cmd_count; cmd_idx = cmd_idx + 1) begin
                    clear_controls();

                    case (stim_mem[si][2:0])
                        3'd0: latch_derivs = 1;  // Latch
                        3'd1: step_x = 1;         // StepX
                        3'd2: step_y = 1;         // StepY
                        3'd3: tile_col_step = 1;  // TileColStep
                        3'd4: tile_row_step = 1;  // TileRowStep
                        default: ;
                    endcase
                    si = si + 1;

                    @(posedge clk);
                    clear_controls();
                    @(posedge clk); // Allow outputs to settle

                    // Compare promoted outputs: 8 colors (16-bit) + Z (16-bit)
                    check16("c0r", out_c0r, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c0g", out_c0g, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c0b", out_c0b, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c0a", out_c0a, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c1r", out_c1r, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c1g", out_c1g, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c1b", out_c1b, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("c1a", out_c1a, exp_mem[ei][15:0]); ei = ei + 1;
                    check16("z",   out_z,   exp_mem[ei][15:0]); ei = ei + 1;

                    // Compare raw ST/Q accumulators (32-bit)
                    check32("s0_acc", s0_acc_out, exp_mem[ei]); ei = ei + 1;
                    check32("t0_acc", t0_acc_out, exp_mem[ei]); ei = ei + 1;
                    check32("s1_acc", s1_acc_out, exp_mem[ei]); ei = ei + 1;
                    check32("t1_acc", t1_acc_out, exp_mem[ei]); ei = ei + 1;
                    check32("q_acc",  q_acc_out,  exp_mem[ei]); ei = ei + 1;
                end
            end
        end

        $display("");
        $display("tb_attr_accum_dt: PASS=%0d FAIL=%0d", pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All outputs match digital twin");
        end
        $finish;
    end

endmodule
