// DT-verified testbench for raster_recip_q
// Loads stimulus and expected output from hex files generated by the digital twin.
// Verification: UNIT-005.04 (Iteration FSM, Per-pixel Reciprocal)

`timescale 1ns/1ps

module tb_recip_q_dt;

    // Clock and reset
    reg clk = 1'b0;
    reg rst_n;
    always #5 clk = ~clk;

    // DUT signals
    reg  [31:0] operand_in;
    reg         valid_in;
    wire [17:0] recip_out;
    wire  [4:0] clz_out;
    wire        valid_out;

    // Instantiate DUT
    raster_recip_q dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .operand_in (operand_in),
        .valid_in   (valid_in),
        .recip_out  (recip_out),
        .clz_out    (clz_out),
        .valid_out  (valid_out)
    );

    // Test vector storage
    parameter MAX_VECTORS = 512;
    reg [31:0] stim_mem [0:MAX_VECTORS-1];
    reg [31:0] exp_mem  [0:MAX_VECTORS-1];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;
    integer count_i;

    initial begin
        $readmemh("../components/rasterizer/rtl/tests/vectors/recip_q_stim.hex", stim_mem);
        $readmemh("../components/rasterizer/rtl/tests/vectors/recip_q_exp.hex", exp_mem);

        num_vectors = 0;
        for (count_i = 0; count_i < MAX_VECTORS; count_i = count_i + 1) begin
            if (stim_mem[count_i] !== 32'hxxxxxxxx)
                num_vectors = count_i + 1;
        end

        rst_n = 0;
        valid_in = 0;
        operand_in = 0;
        repeat (4) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        for (int i = 0; i < num_vectors; i++) begin
            @(posedge clk);
            operand_in = stim_mem[i];
            valid_in = 1;
            @(posedge clk);
            valid_in = 0;

            // Wait for valid_out (2-cycle pipeline)
            @(posedge clk);
            while (!valid_out) @(posedge clk);

            begin
                reg  [4:0] exp_clz;
                reg [17:0] exp_recip;
                exp_clz   = exp_mem[i][22:18];
                exp_recip = exp_mem[i][17:0];

                if (recip_out === exp_recip && clz_out === exp_clz) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: Q=0x%08x expected recip=0x%05x clz=%0d, got recip=0x%05x clz=%0d",
                             i, stim_mem[i], exp_recip, exp_clz, recip_out, clz_out);
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_recip_q_dt: %0d vectors, PASS=%0d FAIL=%0d", num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule
