// DT-verified testbench for raster_recip_area
// Loads stimulus and expected output from hex files generated by the digital twin.
// Verification: UNIT-005.02 (Edge Setup, Reciprocal Area)

`timescale 1ns/1ps

module tb_recip_area_dt;

    // Clock and reset
    reg clk = 1'b0;
    reg rst_n;
    always #5 clk = ~clk;

    // DUT signals
    reg signed [21:0] operand_in;
    reg               valid_in;
    wire       [17:0] recip_out;
    wire        [4:0] area_shift;
    wire              degenerate;
    wire              valid_out;

    // Instantiate DUT
    raster_recip_area dut (
        .clk         (clk),
        .rst_n       (rst_n),
        .operand_in  (operand_in),
        .valid_in    (valid_in),
        .recip_out   (recip_out),
        .area_shift  (area_shift),
        .degenerate  (degenerate),
        .valid_out   (valid_out)
    );

    // Test vector storage
    parameter MAX_VECTORS = 512;
    reg [31:0] stim_mem  [0:MAX_VECTORS-1];
    reg [31:0] exp_mem   [0:MAX_VECTORS-1];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    initial begin
        $readmemh("../components/rasterizer/rtl/tests/vectors/recip_area_stim.hex", stim_mem);
        $readmemh("../components/rasterizer/rtl/tests/vectors/recip_area_exp.hex", exp_mem);

        // First entry is the vector count
        num_vectors = stim_mem[0];

        // Reset
        rst_n = 0;
        valid_in = 0;
        operand_in = 0;
        repeat (4) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        // Drive each vector (index 0 is count, data starts at 1)
        for (int i = 0; i < num_vectors; i++) begin
            @(posedge clk);
            operand_in = stim_mem[i + 1][21:0];
            valid_in = 1;
            @(posedge clk);
            valid_in = 0;

            // Wait for valid_out (2-cycle pipeline)
            @(posedge clk);
            while (!valid_out) @(posedge clk);

            // Compare against expected
            begin
                reg        exp_degen;
                reg  [4:0] exp_shift;
                reg [17:0] exp_recip;
                exp_degen = exp_mem[i + 1][24];
                exp_shift = exp_mem[i + 1][22:18];
                exp_recip = exp_mem[i + 1][17:0];

                if (exp_degen) begin
                    // Degenerate: just check degenerate flag
                    if (degenerate) begin
                        pass_count = pass_count + 1;
                    end else begin
                        $display("FAIL [%0d]: area=0x%06x expected degenerate, got recip=0x%05x shift=%0d",
                                 i, stim_mem[i + 1][21:0], recip_out, area_shift);
                        fail_count = fail_count + 1;
                    end
                end else begin
                    if (recip_out === exp_recip && area_shift === exp_shift && !degenerate) begin
                        pass_count = pass_count + 1;
                    end else begin
                        $display("FAIL [%0d]: area=0x%06x expected recip=0x%05x shift=%0d, got recip=0x%05x shift=%0d degen=%0b",
                                 i, stim_mem[i + 1][21:0], exp_recip, exp_shift,
                                 recip_out, area_shift, degenerate);
                        fail_count = fail_count + 1;
                    end
                end
            end
        end

        // Summary
        $display("");
        $display("tb_recip_area_dt: %0d vectors, PASS=%0d FAIL=%0d", num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule
