// DT-verified testbench for raster_shift_mul_32x11
// Combinational: signed 32-bit × signed 11-bit → signed 32-bit
// Loads test vectors from hex files generated by the digital twin.

`timescale 1ns/1ps

module tb_shift_mul_dt;

    // DUT signals (combinational)
    reg  signed [31:0] a;
    reg  signed [10:0] b;
    wire signed [31:0] p;

    // Instantiate DUT
    raster_shift_mul_32x11 dut (
        .a (a),
        .b (b),
        .p (p)
    );

    // Test vector storage
    // Stimulus format: "AAAAAAAA_BBB" (32-bit a + 11-bit b packed as 64-bit)
    parameter MAX_VECTORS = 512;
    reg [63:0] stim_mem [0:MAX_VECTORS-1];
    reg [31:0] exp_mem  [0:MAX_VECTORS-1];
    integer num_vectors;
    integer pass_count = 0;
    integer fail_count = 0;

    initial begin
        $readmemh("../components/rasterizer/rtl/tests/vectors/shift_mul_stim.hex", stim_mem);
        $readmemh("../components/rasterizer/rtl/tests/vectors/shift_mul_exp.hex", exp_mem);

        // First entry is the vector count
        num_vectors = stim_mem[0][31:0];

        for (int i = 0; i < num_vectors; i++) begin
            a = stim_mem[i + 1][42:11]; // a[31:0] in bits [42:11]
            b = stim_mem[i + 1][10:0];  // b[10:0] in bits [10:0]
            #1;

            begin
                reg signed [31:0] exp_p;
                exp_p = exp_mem[i + 1];

                if (p === exp_p) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("FAIL [%0d]: a=0x%08x b=0x%03x expected 0x%08x, got 0x%08x",
                             i, $unsigned(a), b[10:0], $unsigned(exp_p), $unsigned(p));
                    fail_count = fail_count + 1;
                end
            end
        end

        $display("");
        $display("tb_shift_mul_dt: %0d vectors, PASS=%0d FAIL=%0d", num_vectors, pass_count, fail_count);
        if (fail_count > 0) begin
            $display("FAIL: %0d mismatches detected", fail_count);
            $fatal(1, "Test failed");
        end else begin
            $display("PASS: All vectors match digital twin");
        end
        $finish;
    end

endmodule
